version: 5.0.2.{build}
skip_tags: true
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: Obvs.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: /JaqWVLPjPNAxdRPnQPxqePn+MwzY/Yd2ftPlza0l9GNC16H30puAH/sNZ1De8x3
  skip_symbols: false
  artifact: /.*(?<!symbols)(\.|\.s)nupkg/

for:
# only notify on master builds
-
  branches:
    only:
      - master

  notifications:
    - provider: Webhook
      url:
        # this is the gitter.im webhook address
        secure: xuYg5tCCe3Rpd7EChAHnZspFk0z5DcpksM13lgHz1VQAAc/06ErW1JnEornJrFutLdvohOabNksioR+eta/+aw==
      on_build_success: false
      on_build_failure: false
      on_build_status_changed: true
